const data = [{
  "id": 1,
  "name": "Kathryn Janeway",
  "reportsTo": null,
  "phone": "(555) 924-9726",
  "extension": 8253,
  "hireDate": new Date(2352, 2, 7),
  "species": "Human",
  "position": "Captain",
  "timeInPosition": 1,
  "employees": [{
    "id": 2,
    "name": "Chakotay",
    "reportsTo": 1,
    "phone": "(438) 738-4935",
    "extension": 1155,
    "hireDate": new Date(2371, 3, 3),
    "species": "Human",
    "position": "First Officer",
    "timeInPosition": 1,
    "employees": [{
      "id": 32,
      "name": "Thomas Eugene Paris",
      "reportsTo": 1,
      "phone": "(438) 738-4935",
      "extension": 1155,
      "hireDate": new Date(2371, 3, 3),
      "species": "Vulcan",
      "position": "Lieutenant Commander",
      "timeInPosition": 1,
      },{
        "id": 32,
        "name": "Doctor",
        "reportsTo": 1,
        "phone": "(438) 738-4935",
        "extension": 1155,
        "hireDate": new Date(2371, 3, 3),
        "species": "Emergency Medical Hologram",
        "position": "Chief Medical Officer",
        "timeInPosition": 1,
        },{
          "id": 32,
          "name": "Tuvix",
          "reportsTo": 1,
          "phone": "(438) 738-4935",
          "extension": 1155,
          "hireDate": new Date(2372, 3, 3),
          "species": "Unknown",
          "position": "Lieutenant",
          "timeInPosition": 1,
          },
          {
            "id": 32,
            "name": "B'Elanna Torres",
            "reportsTo": 1,
            "phone": "(438) 738-4935",
            "extension": 1155,
            "hireDate": new Date(2372, 3, 3),
            "species": "Human / Klingon",
            "position": "Lieutenant, Junior Grade",
            "timeInPosition": 1,
            "employees": [{
              "id": 11,
              "name": "Vorick",
              "reportsTo": 32,
              "phone": "(889) 345-2438",
              "extension": 8564,
              "hireDate": new Date(2371, 2, 3),
              "species": "Vulcan",
              "position": "Engineer",
              "timeInPosition": 1,
            },{
                "id": 60,
                "name": "Walter Baxter",
                "reportsTo": 11,
                "phone": "(738) 136-2814",
                "extension": 9353,
                "hireDate": new Date(2371, 4, 21),
                "species": "Human",
                "position": "Engineer",
                "timeInPosition": 2
              }, {
                "id": 78,
                "name": "Maria Gilmore",
                "reportsTo": 11,
                "phone": "(285) 912-5271",
                "extension": 7795,
                "hireDate": new Date(2376, 10, 11),
                "species": "Human",
                "position": "Engineer",
                "timeInPosition": 4
            }]
            },{
      "id": 32,
      "name": "Tuvok",
      "reportsTo": 1,
      "phone": "(438) 738-4935",
      "extension": 1155,
      "hireDate": new Date(2371, 3, 3),
      "species": "Vulcan",
      "position": "Lieutenant Commander",
      "timeInPosition": 1,
      "employees": [{
        "id": 11,
        "name": "Ayala",
        "reportsTo": 32,
        "phone": "(889) 345-2438",
        "extension": 8564,
        "hireDate": new Date(2371, 2, 3),
        "species": "Human",
        "position": "Lieutenant, Junior Grade",
        "timeInPosition": 1,
        "employees": [{
          "id": 60,
          "name": "Timothy Lang",
          "reportsTo": 11,
          "phone": "(738) 136-2814",
          "extension": 9353,
          "hireDate": new Date(2377, 4, 21),
          "species": "Human",
          "position": "Technician",
          "timeInPosition": 2
        }, {
          "id": 78,
          "name": "Harry Kim",
          "reportsTo": 11,
          "phone": "(285) 912-5271",
          "extension": 7795,
          "hireDate": new Date(2371, 10, 11),
          "species": "Human",
          "position": "Tactical Officer",
          "timeInPosition": 4
        }]
      }]
    }]
  }]
}];
export default data;
